export {default as Navbar} from './Navbar/Navbar';
export {default as ImgCarousel} from './ImgCarousel/ImgCarousel';
export {default as Hero} from './Hero/Hero';
export {default as Stats} from './Stats/Stats';
export {default as About} from './About/About';
export {default as PropertyList} from './PropertyList/PropertyList';
export {default as ReviewList} from './ReviewList/ReviewList';
export {default as ContactForm} from './ContactForm/ContactForm';
export {default as Footer} from './Footer/Footer';