import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import classes from '../styles/Home.module.scss';
import {Navbar} from '../components';

const Home: NextPage = () => {
  return (
    <div className={classes.container}>
      <Head>
        <title>CL Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={classes.navbar}>
        <Navbar/>
      </header>
      <main className={classes.main}>
        <div className="heroSection">hero section</div>

      </main>
      <footer>footer</footer>
    </div>
  )
}

export default Home
